version: "3.7"
services:
  service:
    image: pixelflut-server-dotnet
    build: .
    environment:
      - "MaxFps=10"
      - "Width=1280"
      - "Height=720"
      - "JpegQualityPercent=70"
    ports:
      - 8080:8080 # HTTP
      - 8081:8081 # Prometheus
      - 1234:1234 # PixelFlut
    restart: unless-stopped
